In [1]:
import numpy as np

In [2]:
arr1 = np.array([1,2,3,4,5])
print(arr1)
print(arr1[2:])
print(type(arr1))
print(arr1.shape) ##1D array

[1 2 3 4 5]
[3 4 5]
<class 'numpy.ndarray'>
(5,)


In [3]:
arr1[arr1>2]

array([3, 4, 5])

In [4]:
arr1.reshape(1,5)

array([[1, 2, 3, 4, 5]])

In [5]:
arr2 = np.array([[2,3,4,5],[3,4,5,6]])
print(arr2)
print(arr2.shape) 
print(arr2.reshape(4,2))

[[2 3 4 5]
 [3 4 5 6]]
(2, 4)
[[2 3]
 [4 5]
 [3 4]
 [5 6]]


In [6]:
np.arange(5,10).reshape(1,5)

array([[5, 6, 7, 8, 9]])

In [7]:
arr3  = np.arange(1,21).reshape(5,4)

In [8]:
print(np.ones(3))
print(np.ones((3,4)))

[1. 1. 1.]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [9]:
##identity matrix
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [10]:
arr4 = np.arange(0,20).reshape(5,4)
print("Array:\n" , arr4)
print("Shape:" , arr4.shape)
print("Number of dimensions :" , arr4.ndim)
print("Data type:" , arr4.dtype)
print("Item-size (in bytes):" , arr4.itemsize)




Array:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]
Shape: (5, 4)
Number of dimensions : 2
Data type: int64
Item-size (in bytes): 8


### Numpy Vectorized Operations

In [50]:
print(arr2)
arr3 = np.arange(1,9).reshape(2,4)
print(arr3)

[[2 3 4 5]
 [3 4 5 6]]
[[1 2 3 4]
 [5 6 7 8]]


In [54]:
arr1+arr2

ValueError: operands could not be broadcast together with shapes (5,) (2,4) 